blog_jadwal/urls.py
from django.urls import path, include
from .views import (JadwalListView, JadwalDetailView, JadwalCreateView, JadwalUpdateView, JadwalDeleteView, saying)
from . import views

app_name='blog_jadwal'

urlpatterns = [
    path('', JadwalListView.as_view(), name= "home"),
    path("sayhi/",views.saying, name="sayhi"),
    path('jadwaldetail/<int:pk>',JadwalDetailView.as_view(), name= "jadwal-detail"),
    path('new', JadwalCreateView.as_view(), name = "jadwal-form"),
    path('jadwaldetail/<int:pk>/update',JadwalUpdateView.as_view(), name="jadwal-update"),
    path('jadwaldetail/<int:pk>/delete',JadwalDeleteView.as_view(), name="jadwal-delete"),
    path('about', views.about, name= "about"),
]

jadwal_kuliah/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("user.urls")),
    path('', include("blog_jadwal.urls")),
    path('story6/',include("story6.urls")),
    path('story7/',include("story7.urls")),
    path('story8/',include("searchBook.urls"))
    
]

searchBook/urls.py
from django.urls import path, include
from . import views

app_name='searchBook'

urlpatterns = [
    path('', views.homeStory8, name= "home"),
    path("data",views.data, name="data"),
]

story6/urls.py
from django.urls import path, include
from . import views

app_name='story6'

urlpatterns = [
    path('', views.index, name= "index"),
    path("participant/<str:nama>",views.detail_participant,name="detail_participant"),
    path("detail-kegiatan/<str:nama>",views.detail_kegiatan,name="detail_kegiatan"),
    path("add-participant/<int:id>",views.add_participant,name="add_participant"),
    path("add-kegiatan/",views.add_kegiatan,name="add_kegiatan"),
    path("delete/<int:id>", views.delete_kegiatan, name = "delete"),
    path("delete-participant/<str:nama>/<int:id>", views.delete_kegiatan_orang, name = "delete_participant"),
]

user/urls.py
from django.contrib.auth import views as auth_views
from . import views as user_views
from django.urls import path

app_name = 'user'

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

blog_jadwal/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Jadwal(models.Model):
    name = models.CharField(max_length= 50)
    description = models.TextField()
    day = models.CharField(max_length=25)
    time = models.CharField(max_length=25)
    sks = models.IntegerField()
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog_jadwal:jadwal-detail', kwargs={'pk':self.pk})

blog_jadwal/forms.py
from django import forms
from .models import Jadwal

class JadwalCreate(forms.Form):
    
    sks = forms.IntegerField()

    class Meta:
        model = Jadwal
        fields = ['name','description','day','time','sks']

blog_jadwal/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import (ListView, DetailView, CreateView, DeleteView, UpdateView)
from .models import Jadwal
from django.urls import reverse_lazy

# Create your views here.

def home(request):
    context = {
        'jadwals': Jadwal.objects.all()
    }
    return render(request,"blog_jadwal/home.html", context)

def saying(request):
    return render(request,"blog_jadwal/sayhi.html")

class JadwalListView(ListView):
    model = Jadwal
    template_name ='blog_jadwal/home.html'
    context_object_name = 'jadwals'
    ordering = ['name']

class JadwalDetailView(DetailView):
    model = Jadwal

class JadwalCreateView(CreateView):
    model = Jadwal
    fields=['name','description','day','time','sks']

class JadwalUpdateView(UpdateView):
    model = Jadwal
    fields=['name','description','day','time','sks']

class JadwalDeleteView(DeleteView):
    model = Jadwal
    success_url = reverse_lazy("blog_jadwal:home")

def about(request):
    return render(request, "blog_jadwal/about.html",{ "title" : 'About', "subtitle" : 'About'})

blog_jadwal/templates/blog_jadwal/about.html
{% extends 'blog_jadwal/base.html' %}

{% block content %}
    <p class="pt-2 pb-3">Created by Nadya Aprillia</p>
    <p>Web ini untuk membuat jadwal, bisa login juga kalau iseng tetapi data jadwal masih bisa dilihat semua orang :')
    Tujuan utama tetap menyelesaikan tugas story PPW yang ke-5 walaupun belum maksimal, tetapi saya banyak belajar dari
    pembuatan web ini. Adapun teman yang juga membantu saya dalam memberi tips ketika gagal deploy website ini ke heroku 
    and I'm really thankful for that. Dalam web ini, saya banyak menggunakan bootstrap untuk mempercepat proses pengerjaan 
    ("Dikejar deadline") dan menggunakan template dari django seperti DetailView, ListView, dan sebagainya. Permasalahan saat 
    deploy juga terselesaikan dengan pip freeze :)
    </p>
{% endblock content %}

blog_jadwal/templates/blog_jadwal/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    {% if title %}
        <title>Jadwal Kuliah - {{ title }}</title>    
    {% else %}
        <title > Jadwal Kuliah</title>
    {% endif %}
    </head>
    <nav class="navbar navbar-expand-lg bg-custom navbar-dark">
      <ul class="navbar-nav ">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog_jadwal:home' %}">Jadwal Kuliah</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog_jadwal:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog_jadwal:jadwal-form' %}">Add Jadwal</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story6:index' %}">Story 6</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story6:add_kegiatan' %}">Add Kegiatan</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog_jadwal:sayhi' %}">Say Hi</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'searchBook:home' %}">Search Book</a>
        </li>
        </ul>
        <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="#">{{user.username}}</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:login' %}">Log In</a>
          </li>
        {% endif %}
          
      </ul>
    </nav>

  <body>
  
  <div class="container pt-5">
    <h1><u>{{ subtitle }}</u></h1>
   <div class='row' style='text-align: center'> 
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
        {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    </div>
    {% block content %}
    {% endblock content %}
  </div>
      <div class="backgroundimg">
    </div>
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script> {% endcomment %}
    

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS-->
    {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script  type="text/javascript" src="{% static 'js/script.js' %}"></script>
  </body>

</html>

blog_jadwal/templates/blog_jadwal/home.html
{% extends 'blog_jadwal/base.html' %}

{% block content %}
    <h1 class= "pb-4" style="text-align:center"><u>Jadwal Kuliah</u></h1>
    <table class= "table table-striped">
    <thead>
     <tr>
        <th>Mata Kuliah</th>
        <th>SKS</th>
        <th>Hari</th>
        <th>Jam</th>
        <th>Description</th>
     </tr>
    </thead>
    <tbody>
    {% for jadwal in jadwals %}
    <tr>
        <th>{{ jadwal.name }}</th>
        <th>{{ jadwal.sks }} SKS</th>
        <th>{{ jadwal.day }}</th>
        <th>{{ jadwal.time }}</th>
        <th><a href = "{% url 'blog_jadwal:jadwal-detail' jadwal.id %}">See in details</a></th>
    </tr>
    {% empty %}
        <p style = "text-align:center">Belum ditambahkan</p>
    {% endfor %}
    </tbody>
    </table>
    <button type="button" class="btn btn-custom position-button"><a href="{% url 'blog_jadwal:jadwal-form'%}">Add</a></button>
{% endblock content %}

blog_jadwal/templates/blog_jadwal/jadwal_confirm_delete.html
{% extends "blog_jadwal/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Jadwal</legend>
                <h2>Yakin mau hapus jadwal "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog_jadwal:jadwal-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog_jadwal/templates/blog_jadwal/jadwal_detail.html
{% extends 'blog_jadwal/base.html' %}
{% block content %}
<h1 class= "pb-4 "><u>Details</u></h1>
    <h2>{{ jadwal.name }}</h2>
    <p>At {{ jadwal.day }}, around {{jadwal.time}}</p>
    <p>Mempunyai {{ jadwal.sks }} SKS<p>
    <p>{{ jadwal.description }}</p>

<button type="button" class="btn btn-light ">
<a href="{% url 'blog_jadwal:jadwal-update' pk=jadwal.id %}">Update</a>
</button>
<button type="button" class="btn btn-light ">
<a href="{% url 'blog_jadwal:jadwal-delete' pk=jadwal.id %}">Delete</a>
</button>

{% endblock content %}

blog_jadwal/templates/blog_jadwal/jadwal_form.html
{% extends 'blog_jadwal/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
        {% csrf_token %}
            <fieldset class="form-group">
                <legend class = "border-bottom mb-4">Tambahkan/Edit jadwal</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-dark bg-custom" type="submit">Apply Change</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog_jadwal/templates/blog_jadwal/sayhi.html
{% extends 'blog_jadwal/base.html' %}

{% block content %}
    <h1>Hi 
    {% if user.is_authenticated %}
    {{user.username}}
    {% else %}
    Anonim
    {% endif %}
    !</h1>

    <div class="container">
        <p>How's your day?</p>
        <p>Note that this web page "Say Hi" only for testing user authentication UwU</p>
        <img class="sayhi" src="https://files.catbox.moe/x3f3br.jpg"></img>
    </div>


{% endblock content %}