jadwal_kuliah/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("user.urls")),
    path('', include("blog_jadwal.urls")),
    path('story6/',include("story6.urls")),
    path('story7/',include("story7.urls")),
    path('story8/',include("searchBook.urls"))
    
]

story6/urls.py
from django.urls import path, include
from . import views

app_name='story6'

urlpatterns = [
    path('', views.index, name= "index"),
    path("participant/<str:nama>",views.detail_participant,name="detail_participant"),
    path("detail-kegiatan/<str:nama>",views.detail_kegiatan,name="detail_kegiatan"),
    path("add-participant/<int:id>",views.add_participant,name="add_participant"),
    path("add-kegiatan/",views.add_kegiatan,name="add_kegiatan"),
    path("delete/<int:id>", views.delete_kegiatan, name = "delete"),
    path("delete-participant/<str:nama>/<int:id>", views.delete_kegiatan_orang, name = "delete_participant"),
]

user/urls.py
from django.contrib.auth import views as auth_views
from . import views as user_views
from django.urls import path

app_name = 'user'

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

story6/models.py
from django.db import models
from django.shortcuts import reverse
# Create your models here.

class Orang(models.Model) :
    nama_orang = models.CharField(max_length=100, unique=True)

    def __str__(self) :
        return self.nama_orang

    def get_absolute_url(self):
        link_orang = self.nama_orang.replace(" ","-")
        return reverse("story6:detail_participant", args=[link_orang])

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=100, unique=True)
    nama_orang = models.ManyToManyField(Orang,blank=True)

    def __str__(self) :
        return self.nama_kegiatan
    
    def get_absolute_url(self):
        link_kegiatan = self.nama_kegiatan.replace(" ","-")
        return reverse("story6:detail_kegiatan", args=[link_kegiatan])
    

story6/forms.py
from django import forms
from .models import Kegiatan, Orang

class Add_Kegiatan(forms.ModelForm) :
    nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control",
    "placeholder" : "Nama Kegiatan"
    }), label = "")
    class Meta:
        model = Kegiatan
        exclude = ['nama_orang']

class Add_Orang(forms.ModelForm):
    nama_orang = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control",
        "placeholder" : "Nama Participant"
    }), label = "")
    class Meta:
        model = Orang
        fields = "__all__"

story6/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .forms import Add_Kegiatan, Add_Orang
from .models import Kegiatan, Orang
from django.contrib import messages

def index(request):
    context ={
        'kegiatan_obj' : Kegiatan.objects.all(),
        'orang_form' : Add_Orang,
    }
    return render(request, ('story6/index.html'), context)

def add_participant(request,id):
    kegiatan = Kegiatan.objects.get(id=id)
    if request.method == 'POST':
        nama_orang = request.POST["nama_orang"]

        orang_baru, status_new = Orang.objects.get_or_create(nama_orang=nama_orang)
        
        if status_new:
            orang_baru.save()
            kegiatan.nama_orang.add(orang_baru)
            messages.add_message(request,messages.SUCCESS,f"{nama_orang} successfully added to {kegiatan.nama_kegiatan}")
        
        else :
            try:
                kegiatan.nama_orang.get(nama_orang=nama_orang)
                messages.add_message(request, messages.WARNING, f"{nama_orang} has already in {kegiatan.nama_kegiatan}")
            except:
                kegiatan.nama_orang.add(orang_baru)
                messages.add_message(request, messages.SUCCESS, f"{nama_orang} successfully added {kegiatan.nama_kegiatan}")
            

    return redirect(reverse("story6:detail_kegiatan", args=[kegiatan.nama_kegiatan.replace(" ","-")]))

def detail_participant(request,nama):
    name = nama.replace("-"," ")
    orang = get_object_or_404(Orang,nama_orang=name)
    context ={
        'orang' : orang
    }
    return render(request,"story6/detail_participant.html", context)

def detail_kegiatan(request,nama):
    name = nama.replace("-"," ")
    kegiatan = get_object_or_404(Kegiatan,nama_kegiatan=name)
    context = {
        'kegiatan' : kegiatan,
        'orang_form' : Add_Orang,
    }
    return render(request,"story6/detail_kegiatan.html",context)

def add_kegiatan(request):
    if request.method == 'POST':
        kegiatan_forms = Add_Kegiatan(request.POST)
        if kegiatan_forms.is_valid :
            kegiatan_forms.save()
            tes = kegiatan_forms.cleaned_data.get('nama_kegiatan')
            auto = tes.replace(" ", "-")            
            messages.add_message(request,messages.SUCCESS,f"{tes} successfully added")
            return redirect(reverse("story6:detail_kegiatan",args=[auto]))
    
    context ={
        'kegiatan_forms' : Add_Kegiatan,
    }
    return render(request, ('story6/add_kegiatan.html'), context)


def delete_kegiatan(request,id):
    try :
        kegiatan = Kegiatan.objects.get(id=id)
        Kegiatan.objects.filter(id=id).delete()
        messages.add_message(request,messages.SUCCESS,f"{kegiatan.nama_kegiatan} deleted")
        return redirect("story6:index")

    except :
        messages.add_message(request,messages.WARNING,f"{kegiatan.nama_kegiatan} does not exist")
        return redirect("story6:index")

def delete_kegiatan_orang(request,nama,id):
    try :
        orang = Orang.objects.get(nama_orang=nama)
        kegiatan = Kegiatan.objects.get(id=id)
        kegiatan.nama_orang.remove(orang)
        messages.add_message(request,messages.SUCCESS,f"Participant {orang.nama_orang} leaves from {kegiatan.nama_kegiatan}")

    except :
        messages.add_message(request,messages.WARNING,f"{kegiatan.nama_kegiatan} does not exist")

    return redirect(reverse("story6:detail_participant", args=[orang.nama_orang.replace(" ","-")]))






    

story6/templates/story6/add_kegiatan.html
{% extends 'blog_jadwal/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="{% url 'story6:add_kegiatan' %}">
        {% csrf_token %}
            <fieldset class="form-group">
                <legend class = "border-bottom mb-4">Tambahkan Kegiatan</legend>
                {{ kegiatan_forms }}                
            </fieldset>
            <div class="form-group">
                <button class="btn btn-dark bg-custom" type="submit">Add</button>
            </div>
        </form>
    </div>
{% endblock content %}

story6/templates/story6/detail_kegiatan.html
{% extends 'blog_jadwal/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2 class = "border-bottom mb-4">{{ kegiatan.nama_kegiatan }}</h2>
    <ul>
    {% for orang in kegiatan.nama_orang.all  %}
        <li><a href="{{orang.get_absolute_url}}">{{ orang.nama_orang}}</a></li>
    {% empty %}
        <p style = "text-align:center">Belum ditambahkan</p>
    {% endfor %}
    </ul>   
    <div class="content-section">
        <form method="POST" action="{% url 'story6:add_participant' id=kegiatan.id %}">
        {% csrf_token %}
            <fieldset class="form-group">
                <legend class = "border-top mb-4">Add Participant</legend>
                {{ form|crispy }}
                {{orang_form}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-dark bg-custom" type="submit">Apply Change</button>
            </div>
        </form>
        <form method="POST" action="{% url "story6:delete" id=kegiatan.id %}">
        {% csrf_token %}
            <button class="btn btn-danger" type="submit" >Delete</button>
        </form>
    </div>
{% endblock content %}

story6/templates/story6/detail_participant.html
{% extends 'blog_jadwal/base.html' %}


{% block content %}
    <h2 class = "border-bottom mb-4">{{ orang.nama_orang }}</h2>
    <ul>
    {% for kegiatan in orang.kegiatan_set.all  %}
        <form method='POST' action= "{% url 'story6:delete_participant' nama=orang.nama_orang id=kegiatan.id %}">
        {% csrf_token %}
        <li>{{ kegiatan.nama_kegiatan }}<button class="inline btn-danger" value='orang.nama_orang' type="submit">Leave</button></li>
        </form>
    {% empty %}
        <p style = "text-align:center">Belum ada kegiatan</p>
    {% endfor %}
    </ul>   
    <div class="content-section">
    </div>

{% endblock content %}

story6/templates/story6/index.html
{% extends 'blog_jadwal/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1 class= "pb-4" style="text-align:center">Kegiatan</h1>
<div class="card-columns">

{% for kegiatan in kegiatan_obj %}
<div class="card bg-custom2 card-body text-center">
    <h2 class = "border-bottom mb-4"><a href="{% url 'story6:detail_kegiatan' nama=kegiatan.nama_kegiatan %}">{{ kegiatan.nama_kegiatan }}</a></h2>
    <ul>
    {% for orang in kegiatan.nama_orang.all  %}
        <li class= "text-justify">{{ orang.nama_orang}}</li>
    {% endfor %}

    </ul>   
    <div class="content-section">
        <form method="POST" action="{% url 'story6:add_participant' id=kegiatan.id %}">
        {% csrf_token %}
            <fieldset class="form-group">
                <legend>Add Participant</legend>
                {{ form|crispy }}
                {{orang_form}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-dark bg-custom" type="submit">Apply Change</button>
            </div>
        </form>
    </div>
</div>
    {% empty %}
        <p style = "text-align:center">Belum ditambahkan</p>
{% endfor %}

</div>
{% endblock content %}